# application.yml

spring:
  profiles:
    active: ${SPRING_PROFILES_ACTIVE}
  application:
    name: email-service

staffjoy:
  common:
    sentry-dsn: ${SENTRY_DSN}
    deploy-env: ${DEPLOY:V2}
  aliyun-access-key: ${ALIYUN_ACCESS_KEY}
  aliyun-access-secret: ${ALIYUN_ACCESS_SECRET}
